baseurl = "https://cordxclay.com/"
title = "Cord x Clay"
logo = "cordxclaylogo.png"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
googleAnalytics = "UA-120657289-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Cord x Clay"
  copyright = "&copy;2018 Cord x Clay"
  sidebarAbout = [
    "Welcome to <b>CORD X CLAY</b>: a ceramics and fiber art studio owned by two sisters.",
    "Click on the images to browse our portfolio.",
    "Items for purchase are in our <a href=http://www.etsy.com/shop/cordxclay>Etsy shop</a>, but email us at <a href='mailto:cordxclay@gmail.com'>cordxclay@gmail.com</a> if there's something you'd like that isn't in stock!"
  ]

 
[[params.navlinks]]
name = "Home"
url = "portfolio/"
home = true

[[params.navlinks]]
name = "About"
url = "about/"

#sign up to newsletter

  [params.social]
  email         = "cordxclay@gmail.com"
  instagram     = "http://www.instagram.com/cordxclay"

