baseurl = "https://cordxclay.com/"
title = "Cord x Clay"
logo = "cordxclaylogo.png"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-120657289-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Cord x Clay"
  copyright = "&copy;2019 Cord x Clay"
  sidebarAbout = [
    "Welcome to <b>CORD X CLAY</b>: a ceramics and fiber art studio owned by two sisters.",
    ]

[[params.navlinks]]
name = "Weaving Workshops"
url = "weaving_workshop/"

[[params.navlinks]]
name = "Portfolio"
url = "portfolio/"
home = true

[[params.navlinks]]
name = "About Us"
url = "about/"



  [params.social]
  email         = "cordxclay@gmail.com"
  instagram     = "http://www.instagram.com/cordxclay"

